
package Vista;

import Controlador.ConsultaGuiaControlador;
import Utilidades.MostrarPanel;
import java.awt.Color;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author defer
 */
public class panelConsultaGuias extends javax.swing.JPanel {

    ArrayList<Object[]> listaGuias = new ArrayList<>();
    DefaultTableModel modelo;
    ConsultaGuiaControlador ctrl = new ConsultaGuiaControlador();
    
    /**
     * Creates new form panelConsultaGuias
     */
    public panelConsultaGuias() {
        initComponents();
        // Placeholder para el campo de búsqueda
        campoTextoBuscar.setText("Ingrese aquí el número de guía");
        campoTextoBuscar.setForeground(Color.GRAY);

        campoTextoBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campoTextoBuscar.getText().equals("Ingrese aquí el número de guía")) {
                    campoTextoBuscar.setText("");
                    campoTextoBuscar.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campoTextoBuscar.getText().isEmpty()) {
                    campoTextoBuscar.setForeground(Color.GRAY);
                    campoTextoBuscar.setText("Ingrese aquí el número de guía");
                }
            }
        });


        modelo = new DefaultTableModel();
        modelo.addColumn("Nº Guía");
        modelo.addColumn("Fecha");
        modelo.addColumn("Origen");
        modelo.addColumn("Destino");
        modelo.addColumn("Remitente");
        modelo.addColumn("Destinatario");
        modelo.addColumn("Seguro");
        modelo.addColumn("Flete");
        modelo.addColumn("Recargo");
        modelo.addColumn("Valor declarado");        
        modelo.addColumn("Contrareembolso");
        
        listaGuias = ctrl.getDatosVista();
        
        actualizarTabla();
    }


    private void actualizarTabla() {
        modelo.setRowCount(0);
        tablaConsultaGuias = new javax.swing.JTable();
        tablaConsultaGuias.setModel(modelo);
        listaGuias = ctrl.getDatosVista();

        tablaConsultaGuias = new JTable(modelo);
        jScrollPane1.setViewportView(tablaConsultaGuias);

        for (Object[] vector : listaGuias) {

            modelo.addRow(vector);
            tablaConsultaGuias.setModel(modelo);
        }
    }
    
    private DefaultTableModel buscarGuia() {
        String numeroGuia = campoTextoBuscar.getText().trim();
        if (numeroGuia.isEmpty()) {
            // Devuelve una tabla vacía
            DefaultTableModel modeloVacio = new DefaultTableModel(
                new Object[][] {},
                new String[] { "Nº Guía", "Fecha","DNI","Origen","Destino","Remitente","Destinatario","Seguro","Flete","Recargo","Valor Declarado","Contrareembolso"}
            );
            tablaConsultaGuias.setModel(modeloVacio);
            return modeloVacio;
        }
        DefaultTableModel modelo = ctrl.buscarDatosAsociados(numeroGuia);
        tablaConsultaGuias.setModel(modelo);
        return modelo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonEditarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsultaGuias = new javax.swing.JTable();
        campoTextoBuscar = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        botonBuscar1 = new javax.swing.JButton();
        subContent = new javax.swing.JPanel();

        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1500, 775));
        setPreferredSize(new java.awt.Dimension(1500, 775));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setForeground(new java.awt.Color(102, 102, 0));
        content.setMaximumSize(new java.awt.Dimension(1500, 775));
        content.setMinimumSize(new java.awt.Dimension(1200, 600));
        content.setPreferredSize(new java.awt.Dimension(1500, 775));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("LISTA DE GUÍAS REALIZADAS");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 775));

        botonEditarCliente.setBackground(new java.awt.Color(0, 46, 83));
        botonEditarCliente.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        botonEditarCliente.setForeground(new java.awt.Color(127, 241, 82));
        botonEditarCliente.setText("EDITAR CLIENTE");
        botonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarClienteActionPerformed(evt);
            }
        });

        tablaConsultaGuias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablaConsultaGuias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nº Guía", "Fecha", "Origen", "Destino", "Remitente", "Destinatario", "Seguro", "Flete", "Recargo", "Valor declarado", "Contrareembolso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaConsultaGuias);

        campoTextoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoBuscarActionPerformed(evt);
            }
        });

        botonBuscar.setBackground(new java.awt.Color(0, 46, 83));
        botonBuscar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(127, 241, 82));
        botonBuscar.setText("BUSCAR");
        botonBuscar.setMaximumSize(new java.awt.Dimension(32767, 32767));
        botonBuscar.setMinimumSize(new java.awt.Dimension(73, 27));
        botonBuscar.setPreferredSize(new java.awt.Dimension(73, 27));
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonBuscar1.setBackground(new java.awt.Color(0, 46, 83));
        botonBuscar1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        botonBuscar1.setForeground(new java.awt.Color(127, 241, 82));
        botonBuscar1.setText("ORDENAR POR");
        botonBuscar1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        botonBuscar1.setMinimumSize(new java.awt.Dimension(73, 27));
        botonBuscar1.setPreferredSize(new java.awt.Dimension(73, 27));
        botonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoTextoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(botonBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEditarCliente)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        subContent.setBackground(new java.awt.Color(255, 255, 255));
        subContent.setMaximumSize(new java.awt.Dimension(500, 775));
        subContent.setPreferredSize(new java.awt.Dimension(500, 775));

        javax.swing.GroupLayout subContentLayout = new javax.swing.GroupLayout(subContent);
        subContent.setLayout(subContentLayout);
        subContentLayout.setHorizontalGroup(
            subContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        subContentLayout.setVerticalGroup(
            subContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1470, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(subContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(subContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        DefaultTableModel modelo = buscarGuia();
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void campoTextoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoBuscarActionPerformed
        DefaultTableModel modelo = buscarGuia();
    }//GEN-LAST:event_campoTextoBuscarActionPerformed

    private void botonEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarClienteActionPerformed
        int filaSeleccionada = tablaConsultaGuias.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una guía para modificar.");
            return;
        }
        //De acá en adelante la lógica es similar a lo que vamos a tener que hacer
        //para poder abri una ventana con todos los datos de la guía para poder modificarla
        Object[] guia = new Object[] {
            tablaConsultaGuias.getValueAt(filaSeleccionada, 0), // numeroguia
            tablaConsultaGuias.getValueAt(filaSeleccionada, 1), // fecha
            tablaConsultaGuias.getValueAt(filaSeleccionada, 2), // origen
            tablaConsultaGuias.getValueAt(filaSeleccionada, 3), // destino
            tablaConsultaGuias.getValueAt(filaSeleccionada, 4), // remitente
            tablaConsultaGuias.getValueAt(filaSeleccionada, 5), // destinatario
            tablaConsultaGuias.getValueAt(filaSeleccionada, 6), // seguro
            tablaConsultaGuias.getValueAt(filaSeleccionada, 7), // flete
            tablaConsultaGuias.getValueAt(filaSeleccionada,8), // recargo
            tablaConsultaGuias.getValueAt(filaSeleccionada, 9),  // valor declarado
            tablaConsultaGuias.getValueAt(filaSeleccionada, 10),  // contrareembolso
        };
        //MostrarPanel.showPanel(subContent, new panelModificacionClientes(guia, ctrl), 250, 775);
    }//GEN-LAST:event_botonEditarClienteActionPerformed

    private void botonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscar1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonBuscar1;
    private javax.swing.JButton botonEditarCliente;
    private javax.swing.JTextField campoTextoBuscar;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel subContent;
    private javax.swing.JTable tablaConsultaGuias;
    // End of variables declaration//GEN-END:variables
}
