/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.GuiaControlador;
import java.sql.ResultSetMetaData;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author defer
 */
public class panelGuia extends javax.swing.JPanel {

    DefaultTableModel modelo;
    ArrayList<Object[]> listaContenido = new ArrayList<>();

    /**
     * Creates new form panelGuia
     */
    public panelGuia() {
        initComponents();

        modelo = new DefaultTableModel();
        modelo.addColumn("Cantidad");
        modelo.addColumn("Tipo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Peso");

        modelo.setRowCount(0);
        tablaContenido = new javax.swing.JTable();
        tablaContenido.setModel(modelo);
        tablaContenido = new JTable(modelo);

        jScrollPane3.setViewportView(tablaContenido);

        ArrayList<String> localidades = new GuiaControlador().traerLocalidades();
        ArrayList<String> tipos = new GuiaControlador().traerTipo();
        for (String loc : localidades) {
            comboLocalidadesR.addItem(loc);
            comboLocalidadesD.addItem(loc);
        }
        for (String tipo : tipos) {
            comboTipo.addItem(tipo);
        }

        campoNombreR.setVisible(false);
        campoNombreD.setVisible(false);
        campoDomicilioR.setVisible(false);
        campoDomicilioD.setVisible(false);
        campoTelefonoR.setVisible(false);
        campoTelefonoD.setVisible(false);
        comboLocalidadesR.setVisible(false);
        comboLocalidadesD.setVisible(false);

        configurarCampoMoneda(campoSeguro);
        configurarCampoMoneda(campoFlete);
        configurarCampoMoneda(campoRecargo);
        configurarCampoMoneda(campoValorDeclarado);
        configurarCampoMoneda(campoContrareembolso);

        campoSeguro.setValue(0);
        campoFlete.setValue(0);
        campoRecargo.setValue(0);
        campoValorDeclarado.setValue(0);
        campoContrareembolso.setValue(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoDniR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoNombreR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoDomicilioR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoTelefonoR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboLocalidadesR = new javax.swing.JComboBox<>();
        campoDomicilioD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoTelefonoD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboLocalidadesD = new javax.swing.JComboBox<>();
        campoNombreD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoDniD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        campoCantidad = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        campoPeso = new javax.swing.JTextField();
        botonBuscarD = new java.awt.Button();
        botonEmitirGuia = new java.awt.Button();
        botonBuscarR = new java.awt.Button();
        botonAgregarItem = new java.awt.Button();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaContenido = new javax.swing.JTable();
        campoSeguro = new javax.swing.JFormattedTextField();
        campoContrareembolso = new javax.swing.JFormattedTextField();
        campoFlete = new javax.swing.JFormattedTextField();
        campoRecargo = new javax.swing.JFormattedTextField();
        campoValorDeclarado = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(1500, 775));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1500, 775));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DATOS DE LA GUÍA");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DATOS DEL DESTINATARIO");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DATOS DEL REMITENTE");

        campoDniR.setToolTipText("");
        campoDniR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDniRActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("DNI");

        campoNombreR.setToolTipText("");
        campoNombreR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreRActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("NOMBRE COMPLETO");

        campoDomicilioR.setToolTipText("");
        campoDomicilioR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDomicilioRActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("DOMICILIO");

        campoTelefonoR.setToolTipText("");
        campoTelefonoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefonoRActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("TELEFONO");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("LOCALIDAD");

        comboLocalidadesR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLocalidadesRActionPerformed(evt);
            }
        });

        campoDomicilioD.setToolTipText("");
        campoDomicilioD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDomicilioDActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("DOMICILIO");

        campoTelefonoD.setToolTipText("");
        campoTelefonoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefonoDActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("TELEFONO");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("LOCALIDAD");

        comboLocalidadesD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLocalidadesDActionPerformed(evt);
            }
        });

        campoNombreD.setToolTipText("");
        campoNombreD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreDActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("NOMBRE COMPLETO");

        campoDniD.setToolTipText("");
        campoDniD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDniDActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("DNI");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("VALOR DECLARADO");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("CONTRAREEMBOLSO");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("FLETE");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("SEGURO");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("RECARGO");

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("CONTENIDO DEL ENVÍO");

        campoCantidad.setToolTipText("");
        campoCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCantidadActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("CANTIDAD");

        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("TIPO");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("DESCRIPCIÓN");

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        jScrollPane1.setViewportView(campoDescripcion);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("PESO EN KG");

        campoPeso.setToolTipText("");
        campoPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesoActionPerformed(evt);
            }
        });

        botonBuscarD.setActionCommand("BuscarD");
        botonBuscarD.setBackground(new java.awt.Color(0, 46, 83));
        botonBuscarD.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        botonBuscarD.setForeground(new java.awt.Color(127, 241, 82));
        botonBuscarD.setLabel("BUSCAR");
        botonBuscarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarDActionPerformed(evt);
            }
        });

        botonEmitirGuia.setBackground(new java.awt.Color(127, 241, 82));
        botonEmitirGuia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonEmitirGuia.setForeground(new java.awt.Color(39, 57, 131));
        botonEmitirGuia.setLabel("EMITIR GUÍA");
        botonEmitirGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmitirGuiaActionPerformed(evt);
            }
        });

        botonBuscarR.setActionCommand("BuscarR");
        botonBuscarR.setBackground(new java.awt.Color(0, 46, 83));
        botonBuscarR.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        botonBuscarR.setForeground(new java.awt.Color(127, 241, 82));
        botonBuscarR.setLabel("BUSCAR");
        botonBuscarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarRActionPerformed(evt);
            }
        });

        botonAgregarItem.setBackground(new java.awt.Color(0, 46, 83));
        botonAgregarItem.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        botonAgregarItem.setForeground(new java.awt.Color(127, 241, 82));
        botonAgregarItem.setLabel("AGREGAR");
        botonAgregarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarItemActionPerformed(evt);
            }
        });

        tablaContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaContenido);

        campoContrareembolso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContrareembolsoActionPerformed(evt);
            }
        });

        campoValorDeclarado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorDeclaradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(campoDniD)
                            .addComponent(jLabel12)
                            .addComponent(campoNombreD)
                            .addComponent(jLabel9)
                            .addComponent(campoDomicilioD)
                            .addComponent(jLabel10)
                            .addComponent(campoTelefonoD)
                            .addComponent(jLabel11)
                            .addComponent(comboLocalidadesD, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscarD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(campoDniR)
                            .addComponent(jLabel5)
                            .addComponent(campoNombreR)
                            .addComponent(jLabel6)
                            .addComponent(campoDomicilioR)
                            .addComponent(jLabel7)
                            .addComponent(campoTelefonoR)
                            .addComponent(jLabel8)
                            .addComponent(comboLocalidadesR, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscarR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonAgregarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(320, 320, 320)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoValorDeclarado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoRecargo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoFlete, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoSeguro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoContrareembolso)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonEmitirGuia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFlete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoValorDeclarado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoContrareembolso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, 0)
                                        .addComponent(campoDniR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(botonBuscarR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(jLabel5)
                                .addGap(5, 5, 5)
                                .addComponent(campoNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(5, 5, 5)
                                .addComponent(campoDomicilioR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(5, 5, 5)
                                .addComponent(campoTelefonoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboLocalidadesR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(5, 5, 5)
                                        .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonAgregarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBuscarD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDniD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel12)
                        .addGap(5, 5, 5)
                        .addComponent(campoNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addComponent(campoDomicilioD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(5, 5, 5)
                        .addComponent(campoTelefonoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboLocalidadesD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEmitirGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        campoDniR.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void campoDniRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDniRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDniRActionPerformed

    private void campoNombreRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreRActionPerformed

    private void campoDomicilioRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDomicilioRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDomicilioRActionPerformed

    private void campoTelefonoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefonoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefonoRActionPerformed

    private void comboLocalidadesRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocalidadesRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLocalidadesRActionPerformed

    private void campoDomicilioDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDomicilioDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDomicilioDActionPerformed

    private void campoTelefonoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefonoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefonoDActionPerformed

    private void comboLocalidadesDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocalidadesDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLocalidadesDActionPerformed

    private void campoNombreDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreDActionPerformed

    private void campoDniDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDniDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDniDActionPerformed

    private void actualizarTabla() {
        modelo.setRowCount(0);
        tablaContenido = new javax.swing.JTable();
        tablaContenido.setModel(modelo);
        tablaContenido = new JTable(modelo);

        jScrollPane3.setViewportView(tablaContenido);

        Object ob[] = new Object[4];

        ob[0] = campoCantidad.getText().trim();
        ob[1] = comboTipo.getSelectedItem().toString();;
        ob[2] = campoDescripcion.getText().trim();
        ob[3] = campoPeso.getText().trim();

        listaContenido.add(ob);

        for (Object[] vector : listaContenido) {
            modelo.addRow(vector);
            tablaContenido.setModel(modelo);
        }
    }
    private void campoCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCantidadActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoActionPerformed

    private void campoPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesoActionPerformed


    private void botonBuscarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarDActionPerformed
        // TODO add your handling code here:

        String dni = campoDniD.getText();

        String patronDNI = "^[0-9]{7,10}$";

        Pattern patternDNI = Pattern.compile(patronDNI);
        Matcher matcherDNI = patternDNI.matcher(dni);

        if (!dni.trim().isEmpty()) {
            resultadoBusquedaClientes = new GuiaControlador().buscarDNI(dni);

            if (matcherDNI.matches()) {

                if (!resultadoBusquedaClientes.isEmpty()) {
                    campoNombreD.setVisible(true);
                    campoNombreD.setEnabled(false);
                    campoDniD.setEnabled(false);

                    campoDomicilioD.setVisible(true);
                    campoDomicilioD.setEnabled(false);

                    campoTelefonoD.setVisible(true);
                    campoTelefonoD.setEnabled(false);

                    comboLocalidadesD.setVisible(true);
                    comboLocalidadesD.setEnabled(false);

                    campoDniD.setText(resultadoBusquedaClientes.get(0));
                    campoNombreD.setText(resultadoBusquedaClientes.get(1));
                    campoDomicilioD.setText(resultadoBusquedaClientes.get(2));
                    campoTelefonoD.setText(resultadoBusquedaClientes.get(4));
                    comboLocalidadesD.setSelectedItem(resultadoBusquedaClientes.get(3));

                    resultadoBusquedaClientes.clear();
                } else {
                    JOptionPane.showMessageDialog(null, "Cliente no registrado");
                    campoNombreD.setVisible(true);

                    campoDomicilioD.setVisible(true);

                    campoTelefonoD.setVisible(true);

                    comboLocalidadesD.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, "DNI inválido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el DNI");
        }

    }//GEN-LAST:event_botonBuscarDActionPerformed


    private void botonEmitirGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmitirGuiaActionPerformed

        boolean testigo1 = false;
        boolean testigo2 = false;

        String dniRemitente = campoDniR.getText().trim();

        String patronTelefono = "^[0-9]{10}$";

        Pattern patronTel = Pattern.compile(patronTelefono);

        Matcher matcherTel = patronTel.matcher(campoTelefonoR.getText().trim());

        Matcher matcherTelD = patronTel.matcher(campoTelefonoD.getText().trim());

        if (new GuiaControlador().buscarDNI(dniRemitente).isEmpty()) {

            if (!campoNombreR.getText().trim().isEmpty()
                    && !campoDomicilioR.getText().trim().isEmpty()
                    && !campoTelefonoR.getText().trim().isEmpty()
                    && !comboLocalidadesR.getSelectedItem().toString().trim().isEmpty()) {

                if (matcherTel.matches()) {

                    registrarCliente(dniRemitente,
                            campoNombreR.getText().trim(),
                            campoDomicilioR.getText().trim(),
                            campoTelefonoR.getText().trim(),
                            comboLocalidadesR.getSelectedItem().toString().trim()
                    );
                    testigo1 = true;
                    JOptionPane.showMessageDialog(null, "Remitente registrado con éxito.");
                } else {
                    JOptionPane.showMessageDialog(this, "Teléfono remitente inválido.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Complete todos los datos del Remitente.");
            }
        } else {
            testigo1 = true;
        };

        String dniDestinatario = campoDniD.getText().trim();
        if (new GuiaControlador().buscarDNI(dniDestinatario).isEmpty()) {

            if (!campoNombreD.getText().trim().isEmpty()
                    && !campoDomicilioD.getText().trim().isEmpty()
                    && !campoTelefonoD.getText().trim().isEmpty()
                    && !comboLocalidadesD.getSelectedItem().toString().trim().isEmpty()) {

                if (matcherTelD.matches()) {

                    registrarCliente(dniDestinatario,
                            campoNombreD.getText().trim(),
                            campoDomicilioD.getText().trim(),
                            campoTelefonoD.getText().trim(),
                            comboLocalidadesD.getSelectedItem().toString().trim()
                    );
                    testigo2 = true;
                    JOptionPane.showMessageDialog(null, "Destinatario registrado con éxito.");
                } else {
                    JOptionPane.showMessageDialog(this, "Teléfono destinatario inválido.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Complete todos los datos del Destinatario");
            }
        } else {
            testigo2 = true;
        };

        // Obtener la fecha y hora actual del sistema
        LocalDate fechaActual = LocalDate.now(ZoneId.systemDefault());

        // Formatear la fecha a un formato legible
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        //System.out.println(fechaActual.format(formato));

        if (testigo1 && testigo2) {
            if (new GuiaControlador().emitirGuia(
                    fechaActual.format(formato),
                    campoSeguro.getValue().toString().trim(),
                    campoFlete.getValue().toString().trim(),
                    campoRecargo.getValue().toString().trim(),
                    campoValorDeclarado.getValue().toString().trim(),
                    campoContrareembolso.getValue().toString().trim(),
                    campoDniR.getText().trim(),
                    campoDniD.getText().trim(),
                    comboLocalidadesR.getSelectedItem().toString().trim(),
                    comboLocalidadesD.getSelectedItem().toString().trim()
            )) {
                JOptionPane.showMessageDialog(null, "Guía emitida con éxito.");

                campoDniR.setText("");
                campoNombreR.setText("");
                campoDomicilioR.setText("");
                campoTelefonoR.setText("");

                campoDniD.setText("");
                campoNombreD.setText("");
                campoDomicilioD.setText("");
                campoTelefonoD.setText("");

                campoSeguro.setValue(0);
                campoFlete.setValue(0);
                campoRecargo.setValue(0);
                campoValorDeclarado.setValue(0);
                campoContrareembolso.setValue(0);

                campoNombreR.setEnabled(true);
                campoDniR.setEnabled(true);
                campoDomicilioR.setEnabled(true);
                campoTelefonoR.setEnabled(true);
                comboLocalidadesR.setEnabled(true);

                campoNombreD.setEnabled(true);
                campoDniD.setEnabled(true);
                campoDomicilioD.setEnabled(true);
                campoTelefonoD.setEnabled(true);
                comboLocalidadesD.setEnabled(true);

            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo emitir la guía");
        }

    }//GEN-LAST:event_botonEmitirGuiaActionPerformed

    private ArrayList<String> resultadoBusquedaClientes = new ArrayList();

    private void botonBuscarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarRActionPerformed
        // TODO add your handling code here:
        String dni = campoDniR.getText().trim();

        String patronDNI = "^[0-9]{7,10}$";

        Pattern patternDNI = Pattern.compile(patronDNI);
        Matcher matcherDNI = patternDNI.matcher(dni);

        if (!dni.trim().isEmpty()) {
            resultadoBusquedaClientes = new GuiaControlador().buscarDNI(dni);
            if (matcherDNI.matches()) {
                if (!resultadoBusquedaClientes.isEmpty()) {
                    campoNombreR.setVisible(true);
                    campoNombreR.setEnabled(false);
                    campoDniR.setEnabled(false);

                    campoDomicilioR.setVisible(true);
                    campoDomicilioR.setEnabled(false);

                    campoTelefonoR.setVisible(true);
                    campoTelefonoR.setEnabled(false);

                    comboLocalidadesR.setVisible(true);
                    comboLocalidadesR.setEnabled(false);

                    campoDniR.setText(resultadoBusquedaClientes.get(0));
                    campoNombreR.setText(resultadoBusquedaClientes.get(1));
                    campoDomicilioR.setText(resultadoBusquedaClientes.get(2));
                    campoTelefonoR.setText(resultadoBusquedaClientes.get(4));
                    comboLocalidadesR.setSelectedItem(resultadoBusquedaClientes.get(3));

                    resultadoBusquedaClientes.clear();
                } else {
                    JOptionPane.showMessageDialog(null, "Cliente no registrado");
                    campoNombreR.setVisible(true);

                    campoDomicilioR.setVisible(true);

                    campoTelefonoR.setVisible(true);

                    comboLocalidadesR.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El DNI no es válido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el DNI");
        }

    }//GEN-LAST:event_botonBuscarRActionPerformed

    private void botonAgregarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarItemActionPerformed
        // TODO add your handling code here:
        actualizarTabla();
        campoCantidad.setText("");
        campoDescripcion.setText("");
        campoPeso.setText("");
    }//GEN-LAST:event_botonAgregarItemActionPerformed

    private void campoContrareembolsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContrareembolsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContrareembolsoActionPerformed

    private void campoValorDeclaradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorDeclaradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorDeclaradoActionPerformed

    private boolean registrarCliente(String dni, String nombre, String domicilio, String telefono, String localidad) {
        return new GuiaControlador().registrarCliente(dni, nombre, domicilio, telefono, localidad);
    }

    private void configurarCampoMoneda(JFormattedTextField campo) {
        NumberFormat formatoMoneda = NumberFormat.getCurrencyInstance(new Locale("es", "AR"));
        NumberFormatter formatter = new NumberFormatter(formatoMoneda);
        formatter.setAllowsInvalid(false);
        formatter.setMinimum(0.0);
        campo.setFormatterFactory(new DefaultFormatterFactory(formatter));
        campo.setValue(0);
    }

    ;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button botonAgregarItem;
    private java.awt.Button botonBuscarD;
    private java.awt.Button botonBuscarR;
    private java.awt.Button botonEmitirGuia;
    private javax.swing.JTextField campoCantidad;
    private javax.swing.JFormattedTextField campoContrareembolso;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoDniD;
    private javax.swing.JTextField campoDniR;
    private javax.swing.JTextField campoDomicilioD;
    private javax.swing.JTextField campoDomicilioR;
    private javax.swing.JFormattedTextField campoFlete;
    private javax.swing.JTextField campoNombreD;
    private javax.swing.JTextField campoNombreR;
    private javax.swing.JTextField campoPeso;
    private javax.swing.JFormattedTextField campoRecargo;
    private javax.swing.JFormattedTextField campoSeguro;
    private javax.swing.JTextField campoTelefonoD;
    private javax.swing.JTextField campoTelefonoR;
    private javax.swing.JFormattedTextField campoValorDeclarado;
    private javax.swing.JComboBox<String> comboLocalidadesD;
    private javax.swing.JComboBox<String> comboLocalidadesR;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaContenido;
    // End of variables declaration//GEN-END:variables
}
