/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.util.ArrayList;
import Controlador.ClientesControlador;
import static Controlador.ClientesControlador.crearCliente;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Santiago
 */
public class panelAgregarCliente extends javax.swing.JPanel {

    private panelClientes panelPadre;
    /**
     * Creates new form panelAgregarCliente
     */
    public panelAgregarCliente(panelClientes padre) {
        this.panelPadre = padre;
        initComponents();
        // Llenado del combo
        ArrayList<String> localidades = new ClientesControlador().traerLocalidades();
        for (String loc : localidades) {
            comboLocalidad.addItem(loc);
        }

    }

    private void agregarCliente(){
    String dni = TextDNI.getText().trim();
    String nombre = TextNombre.getText().trim();
    String domicilio = TextDomicilio.getText().trim();
    String localidad = (String) comboLocalidad.getSelectedItem();
    String telefono = TextTelefono.getText().trim();

    // Validaciones básicas
    if (dni.isEmpty() || nombre.isEmpty() || domicilio.isEmpty() || telefono.isEmpty() || localidad.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!dni.matches("\\d{7,9}")) {
        JOptionPane.showMessageDialog(this, "El DNI debe contener entre 7 y 9 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!telefono.matches("\\d{10}")) {
        JOptionPane.showMessageDialog(this, "El teléfono debe contener 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    boolean resultado = ClientesControlador.crearCliente(dni, nombre, domicilio, localidad, telefono);
    if (resultado) {
        JOptionPane.showMessageDialog(this, "Cliente agregado correctamente.");
        limpiarCampos();
        if (panelPadre != null) {
            panelPadre.actualizarTabla();}
        
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo agregar el cliente. Puede que ya exista el DNI.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    private void limpiarCampos() {
        TextDNI.setText("");
        TextNombre.setText("");
        TextDomicilio.setText("");
        TextTelefono.setText("");
        comboLocalidad.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextDNI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextDomicilio = new javax.swing.JTextField();
        TextTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonAgregarCliente = new javax.swing.JButton();
        comboLocalidad = new javax.swing.JComboBox<>();
        botonCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(500, 775));
        setMinimumSize(new java.awt.Dimension(500, 775));
        setPreferredSize(new java.awt.Dimension(500, 775));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("DATOS DEL CIENTE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("DNI");

        TextDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDNIActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NOMBRE COMPLETO");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("DOMICILIO");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("TELEFONO");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("LOCALIDAD");

        botonAgregarCliente.setBackground(new java.awt.Color(127, 241, 82));
        botonAgregarCliente.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        botonAgregarCliente.setForeground(new java.awt.Color(0, 46, 83));
        botonAgregarCliente.setText("AGREGAR CLIENTE");
        botonAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarClienteActionPerformed(evt);
            }
        });

        comboLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLocalidadActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(0, 46, 83));
        botonCancelar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(127, 241, 82));
        botonCancelar.setText("CANCELAR");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextDNI)
                            .addComponent(jLabel3)
                            .addComponent(TextNombre)
                            .addComponent(jLabel4)
                            .addComponent(TextDomicilio)
                            .addComponent(TextTelefono)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(comboLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAgregarCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonCancelar)
                                .addGap(31, 31, 31)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(botonAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarClienteActionPerformed
        agregarCliente();
    }//GEN-LAST:event_botonAgregarClienteActionPerformed

    private void TextDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDNIActionPerformed

    private void comboLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocalidadActionPerformed

    }//GEN-LAST:event_comboLocalidadActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextDNI;
    private javax.swing.JTextField TextDomicilio;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextTelefono;
    private javax.swing.JButton botonAgregarCliente;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JComboBox<String> comboLocalidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
